spring:
  datasource:
    jdbc-url: jdbc:h2:tcp://localhost/~/eatmate
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  redis:
    host: localhost
    port: 6379

#파일 업로드 경로
file:
  dir:
    account: C:/TeamProject/eatmate/img/profileimg
    post: C:/TeamProject/eatmate/img/postimg
    team: C:/TeamProject/eatmate/img/teamimg
    teamPost: C:/TeamProject/eatmate/img/teampostimg

#OPEN API 설정
kakao:
  client:
    id: 4d77a5adb4a0ec1e3c0b6b28c5f48284
    secret: cn8DCCeldGOtP4xsKpmLskR4pPTD7zwO

naver:
  api:
    client_id:
    client_secret:
    url:
