spring:
  datasource:
    jdbc-url: jdbc:h2:tcp://localhost/~/eatmate
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

#파일 업로드 경로
file:
  dir:
    account: C:/TeamProject/eatmate/eatmate/img/profileimg
    review: C:/TeamProject/eatmate/eatmate/img/reviewimg

#OPEN API 설정
kakao:
  api:
    client_id:
    client_secret:
    url:

naver:
  api:
    client_id:
    client_secret:
    url:
