spring:
  datasource:
    jdbc-url: jdbc:h2:tcp://localhost/~/eatmate
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client.id}  # 기존 설정을 그대로 활용합니다.
            client-secret: ${kakao.client.secret}
            client-name: Kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


#파일 업로드 경로
file:
  dir:
    account: C:/TeamProject/eatmate/img/profileimg
    team: C:/TeamProject/eatmate/img/teamimg
    teamPost: C:/TeamProject/eatmate/img/teampostimg

#OPEN API 설정
kakao:
  client:
    id: e14cb05b33510d6d6fb59bc77f202156
    secret: jBgKKQxp5icYdE8NdbWWP7wbJjTFMhcJ

naver:
  api:
    client_id:
    client_secret:
    url:
