# 운영
spring:
  config:
    activate:
      on-profile: prod
  server:
    port: 80
  #DB - 1
  datasource:
    jdbc-url: jdbc:mysql://bonapetit.cnucyg8w8tyu.ap-northeast-2.rds.amazonaws.com:3306/bonapetit?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: bonapetit0902
  #jpa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect     
  #redis
  redis:
    host: localhost
    port: 6379
  #jwt 토큰
  jwt:
    secret: jIxcYARLKbjsUFEPksAcekGXpubvTVL+UxuNL68nqpE=
  #devTools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  #Security 및 Oauth 설정
  security:
    oauth2:
      client:
        registration:
          #카카오
          kakao:
            client-id: ${kakao.client.id}
            client-secret: ${kakao.client.secret}
            client-name: Kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "https://api.bonappetit.p-e.kr/login/oauth2/code/kakao"

          #네이버
          naver:
            client-id: ${naver.client.id}
            client-secret: ${naver.client.secret}
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - name

          # 구글
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
            client-name: Google
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          #네이버
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

#OPEN API 설정
kakao:
  client:
    id: fde79d1d4d914a0bafc33c44c782740b
    secret: QnDQdaUkBbH4zoppp9t42xTVzSnHNjKL
naver:
  client:
    id: vxzSX7hpBWdUiZGim9aX
    secret: STysDb2fkw
google:
  client:
    id: 22110496570-9okorgjcubqkb5qvfthfu398k6et0gg0.apps.googleusercontent.com
    secret: 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

#파일 업로드 경로
file:
  dir:
    account: C:/TeamProject/eatmate/img/profileimg
    team: C:/TeamProject/eatmate/img/teamimg
    teamPost: C:/TeamProject/eatmate/img/teampostimg

