spring:
  datasource:
    jdbc-url: jdbc:h2:tcp://localhost/~/eatmate
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  redis:
    host: localhost
    port: 6379

#파일 업로드 경로
file:
  dir:
    account: C:/TeamProject/eatmate/eatmate/img/accountimg
    team: C:/TeamProject/eatmate/eatmate/img/teamimg
    teamPost: C:/TeamProject/eatmate/eatmate/img/teamPostimg
    post: C:/TeamProject/eatmate/eatmate/img/postimg

#OPEN API 설정
kakao:
  client:
    id: 8a8d1936aa61819a2672c17f1d6e3762
    secret: H2j4hdlF3Skywdp7ZEVCv3siwSTMkfdN

naver:
  api:
    client_id:
    client_secret:
    url:
