global:
  scrape_interval: 1m
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: 'bonappetit-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['3.36.34.213:80', '13.209.176.136:80', '13.125.189.40:80']
        scrape_interval: 1m
